name: CI/CD Farmers Market

on:
  push:
    branches: [ "develop" ]

jobs:
  # --- ПЕРВЫЙ ЭТАП: СБОРКА И ПУШ ОБРАЗА ---
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          # Dockerfile теперь в корне репозитория
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cursedtk:latest

  # --- ВТОРОЙ ЭТАП: ДЕПЛОЙ НА СЕРВЕР ---
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. Обновляем фронтенд (копируем из папки frontend/ репозитория в /static на сервере)
      - name: Copy frontend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "frontend/*"
          target: "/home/devops/course/static"
          strip_components: 1 # Отрезает 'frontend/', файлы ложатся прямо в static/

      # 2. Обновляем конфиг Nginx
      - name: Update Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "nginx/nginx.conf"
          target: "/home/devops/course/nginx"
          strip_components: 1

      # 3. Обновляем docker-compose.yaml в корне ~/course
      - name: Update docker-compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yaml"
          target: "/home/devops/course"

      # 4. Перезапуск контейнеров
      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/course
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
